// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4LiHHdgnLqOHR1c9IBA188UL9I9BEAhU',
    appId: '1:898244754613:web:6341d2534151a1dbe4d2fc',
    messagingSenderId: '898244754613',
    projectId: 'powertrack-d5d35',
    authDomain: 'powertrack-d5d35.firebaseapp.com',
    databaseURL: 'https://powertrack-d5d35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powertrack-d5d35.firebasestorage.app',
    measurementId: 'G-CHXKP9SLE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-z74FFf6YiTrixWELZYuHbiZdhE4enfQ',
    appId: '1:898244754613:android:aa50bcf6c7615b43e4d2fc',
    messagingSenderId: '898244754613',
    projectId: 'powertrack-d5d35',
    databaseURL: 'https://powertrack-d5d35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powertrack-d5d35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxfO8RB3I6HYC80d0ixDbR8OatfDsRGQg',
    appId: '1:898244754613:ios:fccf99613afe4c1ae4d2fc',
    messagingSenderId: '898244754613',
    projectId: 'powertrack-d5d35',
    databaseURL: 'https://powertrack-d5d35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powertrack-d5d35.firebasestorage.app',
    iosBundleId: 'com.example.powerTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxfO8RB3I6HYC80d0ixDbR8OatfDsRGQg',
    appId: '1:898244754613:ios:fccf99613afe4c1ae4d2fc',
    messagingSenderId: '898244754613',
    projectId: 'powertrack-d5d35',
    databaseURL: 'https://powertrack-d5d35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'powertrack-d5d35.firebasestorage.app',
    iosBundleId: 'com.example.powerTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4LiHHdgnLqOHR1c9IBA188UL9I9BEAhU',
    appId: '1:898244754613:web:425fcde33d6bf1f8e4d2fc',
    messagingSenderId: '898244754613',
    projectId: 'powertrack-d5d35',
    authDomain: 'powertrack-d5d35.firebaseapp.com',
    storageBucket: 'powertrack-d5d35.firebasestorage.app',
    measurementId: 'G-V9V27PB03Q',
  );
}